### ISSUE TITLE
Feature request: formatting

### ISSUE THREAD

**Issue by HaanJde** [Chris00/ocaml-csv#10]
Thanks for the good work, saved me a lot of time.

Feature request: using cvstool I missed an easy and speedy formatting posibility. I solved it the end with the call posibility using a bash function: "fc2 ()  {      echo '"'$1'", "'$8'"' }". The speed is very low, though. How about adding a column-spec in which every non-numeric is just printed? eg.

     '"1", "8"\n'

or with quotes:

      '"'1'", "'8'"\n'

I am a C programmer, not ocaml, or would have hacked something up to merge.

**Comment by Chris00** [comment]
I have pushed some code to implement this feature.  Could you please test it before I release a new OPAM package?  Thanks.

**Comment by Chris00** [comment]
@HaanJde Did you have time to try it?

**Comment by HaanJde** [comment]
Hi Chris00,

    sorry, didn't take the time. Planned in for tomorrow morning. I'll give
you feedback by noon.
Promised.

Jan.

On Sun, Oct 11, 2015 at 10:14 AM, Christophe Troestler <
notifications@github.com> wrote:

> @HaanJde <https://github.com/HaanJde> Did you have time to try it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Chris00/ocaml-csv/issues/10#issuecomment-147171635>.
>



-- 
"Piracy is simply demand where supply does not exist."

**Comment by HaanJde** [comment]
Unable to test : normally working from Ubuntu LTS (14.04 in this case). Building a 15.04 vm eventually ended in

"me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >make
oasis setup -setup-update dynamic
ocaml setup.ml -configure --enable-tests
ocamlfind: Package `bytes' not found
W: Field 'pkg_bytes' is not set: Command ''/usr/bin/ocamlfind' query -format %d bytes > '/tmp/oasis-e8fe90.txt'' terminated with error code 2
E: Cannot find findlib package bytes
E: Failure("1 configuration error")
Makefile:18: recipe for target 'configure' failed
make: *** [configure] Error 1
me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >"

After installing a new ocaml from ppa, ended up with this: 

me@laptop:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >make
ocaml setup.ml -configure --enable-tests
Cannot find file topfind.
Unknown directive `require'.
Makefile:18: recipe for target 'configure' failed
make: *** [configure] Error 2
me@laptop:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >apt-cache search topfind
me@laptop:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >apt-file search topfind
libfindlib-ocaml-dev: /usr/lib/ocaml/findlib/topfind.cmi
libfindlib-ocaml-dev: /usr/lib/ocaml/findlib/topfind.mli
libfindlib-ocaml-dev: /usr/lib/ocaml/topfind
me@laptop:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >sudo apt install libfindlib-ocaml-dev:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libfindlib-ocaml-dev : Depends: libfindlib-ocaml-ugx61
                        Depends: ocaml-nox-4.01.0
                        Recommends: ocaml-findlib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >sudo apt install libfindlib-ocaml-dev libfindlib-ocaml-ugx61 ocaml-nox-4.01.0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfindlib-ocaml' instead of 'libfindlib-ocaml-ugx61'
Package ocaml-nox-4.01.0 is a virtual package provided by:
  ocaml-nox 4.01.0-4ubuntu1 [Not candidate version]

E: Package 'ocaml-nox-4.01.0' has no installation candidate
me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >

**Comment by Chris00** [comment]
On Mon, 12 Oct 2015 02:23:37 -0700, Jan de Haan wrote:
> 
> Unable to test : normally working from Ubuntu LTS (14.04 in this case).
> Building a 15.04 vm eventually ended in
> 
> "me@vm1504:/home/me/dat/csvtool/
> ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >make
> oasis setup -setup-update dynamic
> ocaml setup.ml -configure --enable-tests
> ocamlfind: Package `bytes' not found

You need to install the package "bytes":

opam install base-bytes

> After installing a new ocaml from ppa, ended up with this:
> 
> me@laptop:/home/me/dat/csvtool/
> ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >make
> ocaml setup.ml -configure --enable-tests
> Cannot find file topfind.
> Unknown directive `require'.

You need to install "ocamlfind":

opam install ocamlfind

**Comment by HaanJde** [comment]
Hum, that didn't work well. See below. Installing the latest ocaml from ppa wasnt such a good idea, maybe. Should I do a clean reinstall?

me@laptop:/home/me >ssh vm1504
Welcome to Ubuntu 15.04 (GNU/Linux 3.19.0-30-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Mon Oct 12 13:32:46 CEST 2015

  System load:  0.04              Processes:           77
  Usage of /:   34.1% of 6.76GB   Users logged in:     0
  Memory usage: 22%               IP address for eth0: 192.168.246.182
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

Last login: Mon Oct 12 10:56:36 2015 from laptop.local.mydomain.tld
me@vm1504:/home/me >cd dat/csvtool/
me@vm1504:/home/me/dat/csvtool >opam install base-bytes
Your system compiler has been changed. Do you want to upgrade your OPAM installation ? [Y/n] y

=-=- Upgrading system -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[WARNING] base-bytes.legacy is not available because it requires OCaml < 4.02.0. Skipping.
The following actions will be performed:
  ∗  install base-threads  base 
  ∗  install ocamlfind     1.5.5
  ∗  install base-unix     base 
  ∗  install base-bigarray base 
  ∗  install base-bytes    base               [required by csv]
  ∗  install csv           1.4.1
===== ∗  6 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[csv] Archive in cache
[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
∗  installed ocamlfind.1.5.5
∗  installed base-bytes.base
∗  installed csv.1.4.1
Done.

System update successful. Go on with "opam install base-bytes" ? [Y/n] y
[NOTE] Package base-bytes is already installed (current version is base).
me@vm1504:/home/me/dat/csvtool >opam install ocamlfind
[NOTE] Package ocamlfind is already installed (current version is 1.5.5).
me@vm1504:/home/me/dat/csvtool >ls -al
total 60
drwxrwxr-x 3 jan jan  4096 Oct 12 11:01 .
drwxrwxr-x 3 jan jan  4096 Oct 12 10:55 ..
-rw-rw-r-- 1 jan jan 49061 Oct 12 10:56 7e7bb55a74c54b972ababa77f49ddfa25e0c7762.zip
drwxrwxr-x 5 jan jan  4096 Oct 12 11:03 ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762
me@vm1504:/home/me/dat/csvtool >cd ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762/
me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >make
ocaml setup.ml -configure --enable-tests
No such package: oasis.dynrun
File "setup.ml", line 34, characters 5-16:
Error: Unbound module OASISDynRun
Makefile:18: recipe for target 'configure' failed
make: *** [configure] Error 2
me@vm1504:/home/me/dat/csvtool/ocaml-csv-7e7bb55a74c54b972ababa77f49ddfa25e0c7762 >

**Comment by Chris00** [comment]
>  No such package: oasis.dynrun

You need to install `oasis` (not needed for the packaged version but it is for the development version).

**Comment by HaanJde** [comment]
I did:

me@vm1504:/home/me/dat/cvstool/ocaml-csv-master >dpkg -l liboasis-ocaml liboasis-ocaml-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  liboasis-ocaml                            0.4.4-2build1             amd64                     Build-system generation for OCaml projects -- runtime
ii  liboasis-ocaml-dev                        0.4.4-2build1             amd64                     Build-system generation for OCaml projects -- development files
me@vm1504:/home/me/dat/cvstool/ocaml-csv-master >dpkg -L liboasis-ocaml liboasis-ocaml-dev | grep dynrun
/usr/lib/ocaml/oasis/dynrun.cma
/usr/lib/ocaml/oasis/dynrun.cmxs
/usr/lib/ocaml/oasis/dynrun.cmxa
/usr/lib/ocaml/oasis/dynrun.a
me@vm1504:/home/me/dat/cvstool/ocaml-csv-master >dpkg -L liboasis-ocaml liboasis-ocaml-dev | grep dynrun | xargs ls -al
-rw-r--r-- 1 root root  9766 Nov  1  2014 /usr/lib/ocaml/oasis/dynrun.a
-rw-r--r-- 1 root root 12749 Nov  1  2014 /usr/lib/ocaml/oasis/dynrun.cma
-rw-r--r-- 1 root root  3230 Nov  1  2014 /usr/lib/ocaml/oasis/dynrun.cmxa
-rw-r--r-- 1 root root 18440 Nov  1  2014 /usr/lib/ocaml/oasis/dynrun.cmxs
me@vm1504:/home/me/dat/cvstool/ocaml-csv-master >make
oasis setup -setup-update dynamic
ocaml setup.ml -configure --enable-tests
No such package: oasis.dynrun
File "setup.ml", line 34, characters 0-16:
Error: Unbound module OASISDynRun
Makefile:18: recipe for target 'configure' failed
make: *** [configure] Error 2
me@vm1504:/home/me/dat/cvstool/ocaml-csv-master >

**Comment by Chris00** [comment]
What says `echo $OCAML_TOPLEVEL_PATH`?

**Comment by Chris00** [comment]
And `ocamlfind query oasis.dynrun`?

You may want to remove the packages of the distribution and install `ocamlfind` and `oasis` using `opam`.

**Comment by HaanJde** [comment]
me@vm1504:/home/me >echo $OCAML_TOPLEVEL_PATH
/home/me/.opam/system/lib/toplevel
me@vm1504:/home/me >ocamlfind query oasis.dynrun
ocamlfind: Package `oasis.dynrun' not found
me@vm1504:/home/me >

**Comment by Chris00** [comment]
On Fri, 16 Oct 2015 01:25:05 -0700, Jan de Haan wrote:
> 
> me@vm1504:/home/me >echo $OCAML_TOPLEVEL_PATH
> /home/me/.opam/system/lib/toplevel
> me@vm1504:/home/me >ocamlfind query oasis.dynrun
> ocamlfind: Package `oasis.dynrun' not found

I suspect that your OPAM installed ocamlfind does not find the system wide oasis.  Remove the Debian package and install oasis through OPAM.

**Comment by HaanJde** [comment]
real	2m4.905s
vs.
   real	0m0.153s
a 816 times faster result. I wish all my improvements were that efective. Thanks.

me@laptop:/home/me/dat/Projects/f22/poging4 >dpkg -S $(which csvtool)
csvtool: /usr/bin/csvtool
me@laptop:/home/me/dat/Projects/f22/poging4 >dpkg -l csvtool
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  csvtool                                   1.3.3-1                   amd64                     handy command line tool for handling CSV files
me@laptop:/home/me/dat/Projects/f22/poging4 >ls -al
total 33784
drwxrwxr-x 2 me  me      4096 okt 12 09:24 .
drwxrwxr-x 6 me  me      4096 sep 30 11:11 ..
-rw-rw-r-- 1 me  me        89 sep 30 17:23 func.rc
-rw-r--r-- 1 me  me  10622827 sep 30 11:16 index-sdd-20150930111308.txt
-rw-r--r-- 1 me  me  10622971 sep 30 11:20 index-sde-20150930111659.txt
-rw-rw-r-- 1 me  me   6663227 sep 30 17:27 sdd-ns
-rw-rw-r-- 1 me  me   6663309 sep 30 17:26 sde-ns
-rw-rw-r-- 1 me  me      2158 sep 30 13:49 unique-files.txt
me@laptop:/home/me/dat/Projects/f22/poging4 >. ./func.rc 
me@laptop:/home/me/dat/Projects/f22/poging4 >cat func.rc 
function fc2 {
          echo '"'$1'", "'$8'"'
          echo ''
        }
export -f fc2
me@laptop:/home/me/dat/Projects/f22/poging4 >export -f fc2
me@laptop:/home/me/dat/Projects/f22/poging4 >time csvtool call fc2 - < index-sde-20150930111659.txt > out-1.3.3-1

real	2m4.905s
user	0m11.198s
sys	1m40.657s
me@laptop:/home/me/dat/Projects/f22/poging4 >cat index-sde-20150930111659.txt | wc -l
63354
me@laptop:/home/me/dat/Projects/f22/poging4 >cat out-1.3.3-1 | wc -l
126708
me@laptop:/home/me/dat/Projects/f22/poging4 >
me@laptop:/home/me/dat/Projects/f22/poging6 >time ./csvtool-new format '"%(1)", "%(8)"\n\n' - < ../poging4/index-sde-20150930111659.txt > out.txt

real	0m0.153s
user	0m0.137s
sys	0m0.016s
me@laptop:/home/me/dat/Projects/f22/poging6 >ls -al ../poging4 out.txt
-rw-rw-r-- 1 me  me  6663309 okt 16 13:21 out.txt

../poging4:
total 40296
drwxrwxr-x 2 me  me      4096 okt 12 09:35 .
drwxrwxr-x 8 me  me      4096 okt 16 13:16 ..
-rw-rw-r-- 1 me  me        89 sep 30 17:23 func.rc
-rw-r--r-- 1 me  me  10622827 sep 30 11:16 index-sdd-20150930111308.txt
-rw-r--r-- 1 me  me  10622971 sep 30 11:20 index-sde-20150930111659.txt
-rw-rw-r-- 1 me  me   6663309 okt 12 09:27 out-1.3.3-1
-rw-rw-r-- 1 me  me      1964 okt 12 09:35 out-1.3.3-1_verslag.txt
-rw-rw-r-- 1 me  me   6663227 sep 30 17:27 sdd-ns
-rw-rw-r-- 1 me  me   6663309 sep 30 17:26 sde-ns
-rw-rw-r-- 1 me  me      2158 sep 30 13:49 unique-files.txt
me@laptop:/home/me/dat/Projects/f22/poging6 >diff out.txt ../poging4/sde-ns
me@laptop:/home/me/dat/Projects/f22/poging6 >echo $?
0
me@laptop:/home/me/dat/Projects/f22/poging6 >

**Comment by Chris00** [comment]
On Fri, 16 Oct 2015 04:32:17 -0700, Jan de Haan wrote:
> 
> real 2m4.905s
> vs.
> real 0m0.153s
> a 816 times faster result. I wish all my improvements were that efective.

Good. :)

Now the questions are:
- Is the format language expressive enough?
- Is there a need for some escaping?  At the moment the raw column value is printed but maybe there is a need in some situations to quote some chars?

**Comment by HaanJde** [comment]
The format is enough for my purposes as I am limited in my project to standards based filenames. In my humble opinion the input and any problems with it, are the users' responsibility.

On a broader scale, I think that _any_ input should be allowed and posible, upto and including binary, but that is neither my nor your responsibility. As far as I see, all problems with in- and output, being resolved with escapes of diferent forms, are a result of limits of previous systems, where nobody ever took to the task of designing a system allowing for all kinds of input.

Thanks again for your improvement, saves me a lot of time.

**Comment by Chris00** [comment]
New package pending:  https://github.com/ocaml/opam-repository/pull/5006
