### ISSUE TITLE
Stack_overflow

### ISSUE THREAD

**Issue by HaanJde** [Chris00/ocaml-csv#13]
Probably due to size limitations somewhere...

me@laptop:/home/me >zcat /media/me/Me/dat/backup-somelaptop/snapshot.txtgz | head -n 6 | csvtool col 5 -
drwxr-xr-x
drwxr-xr-x
drwxr-xr-x
drwxr-xr-x
-rwxr-xr-x
-rw-r--r--
me@laptop:/home/me >zcat /media/me/Me/dat/backup-somelaptop/snapshot.txtgz | csvtool col 5 - | sort | uniq -c
Fatal error: exception Stack_overflow
me@laptop:/home/me >zcat /media/me/Me/dat/backup-somelaptop/snapshot.txtgz | csvtool col 5 - > output.txt
Fatal error: exception Stack_overflow
me@laptop:/home/me >echo $?
2
me@laptop:/home/me >zcat /media/me/Me/dat/backup-somelaptop/snapshot.txtgz | wc -l
1244707
me@laptop:/home/me >zcat /media/me/Me/dat/backup-somelaptop/snapshot.txtgz | wc -c
254590008
me@laptop:/home/me >dpkg -l csvtool
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  csvtool                                         1.4.2-1                      amd64                        handy command line tool for handling CSV files
me@laptop:/home/me >

**Comment by Chris00** [comment]
It is likely to be some non-tail-recursive iteration along a list.  I'll take a look but to help locating the culprit, would you upload somewhere a(n) (anonymized) file that triggers the issue?

**Comment by HaanJde** [comment]
https://www.dropbox.com/s/9nymduzm5zdn7dm/snapshot.txtgz?dl=0

**Comment by Chris00** [comment]
Done.

**Comment by HaanJde** [comment]
Deleted.

**Comment by Chris00** [comment]
New release **for opam** [pending](https://github.com/ocaml/opam-repository/pull/6453).  It may take some time until it makes it to the Debian/Ubuntu repository — take a look at [opam](https://opam.ocaml.org/), it's well worth it.
