### ISSUE TITLE
How to Write Out Quoted Fields?

### ISSUE THREAD

**Issue by ode79** [Chris00/ocaml-csv#16]
I have read in a CSV with quoted fields using CSV.load but when I write out the CSV with CSV.save, all the quotes are stripped.

How do I write out the file and retain the quotes?

Thanks

**Comment by Chris00** [comment]
You can't.   Quotes are only added **when** they are **needed**.  The output file is equivalent to the original one in any case, so all tools that understand CSV should parse the two in the same way.

**Comment by Chris00** [comment]
The only thing that could be done would be an *option* to *force* quoting of all fields on output but I do not see the point, so you need to explain a strong enough motivation.

**Comment by ode79** [comment]
I thought quoting had to be all or nothing for all fields, I wasn't aware that certain fields can be quoted when necessary. Playing around with csvtool and my file I now see this is possible.

The only arguments I have for forcing quoting to me are:

1. Ease of readability. - With quoted fields, just opening the file to look something up manually in the file seems more readable with the clear separation of quotes. Although using commas with spaces around them may be as good or almost as good.

2. Consistency.
    The file produced by this library may be also be used with another piece of tooling and that could be expecting quoted fields. From what I've read CSV is not a well defined file-format and relying on tooling to be able to handle files with some fields quoted, and some not may not be a good assumption.

3. Expected behaviour of users coming from other languages.
    I remember writing code in Python to work on the same file as I'm working on now and Python either kept the quotes by default or I had the option to keep them.
    I believe I had the same behaviour in Clojure.

If you don't find any of these reasons compelling to add the option to force quoting you can close the issue.

Thanks

**Comment by Chris00** [comment]
> using commas with spaces around them may be as good or almost as good.

This is not a good idea: spaces are normally part of the unquoted fields — they are discarded by default by the `Csv` module because the first versions of the module used to do so but you can keep them with `~strip:false`.

**Comment by Chris00** [comment]
For Python, I followed the [example](https://docs.python.org/3/library/csv.html#csv.DictWriter) and the generated file does not contain quotes.   But there is indeed [csv.QUOTE_ALL](https://docs.python.org/3/library/csv.html#csv.QUOTE_ALL) to force quoting of all fields.

**Comment by Chris00** [comment]
I must say that I am not really buying your arguments — for example, CSV files are IMHO more readable without quotes and should be read in the spreadsheet; problems with some tooling is usually due to quoted fields (with badly escaped quotes), not to the mix of quoted and unquoted fields;... — but introducing an optional argument `~quote_all` is easy enough.

**Comment by Chris00** [comment]
Could you please test it to make sure it suits your needs?

**Comment by ode79** [comment]
Yes, the changes you made works for me thanks.
