### ISSUE TITLE
Release tar.gz for version 1.7

### ISSUE THREAD

**Issue by ibor** [Chris00/ocaml-csv#20]
The release page lists source and release archives for most version. For 1.7 it only provides the source archives. Is that intentional? Might you be able to add the release tarball, which was originally available from https://math.umons.ac.be/anum/software/csv/csv-1.7.tar.gz ?

Context: https://github.com/NixOS/nixpkgs/issues/30476

**Comment by Chris00** [comment]
I di a checkout and generated a tarball (please check that it works).

**Comment by ibor** [comment]
Works for me. Thanks a lot!
