### ISSUE TITLE
Example file not exhaustive 

### ISSUE THREAD

**Issue by adayoung111** [Chris00/ocaml-csv#24]
I want to use your library to write a list of strings to a CSV file. I've read the signature file for this library and I am a bit confused on how to create a `out_channel` and write strings to it. The `example.ml` currently only includes an example on how to read from a CSV file. I'm wondering if you can add another example of how to create and write to a CSV file. Thanks!

**Comment by struktured** [comment]
@adayoung111:

```OCaml
Csv.save "file.csv" (Csv.of_array [|[|"a";"b"|]|])
```

Full signature / documentation:

```OCaml
val save : ?separator:char -> ?backslash_escape: bool -> ?excel_tricks:bool ->
           ?quote_all:bool ->
           string -> t -> unit
  (** [save fname csv] saves the [csv] data to the file [fname]. *)
```

**Comment by Chris00** [comment]
Some lines of code have been added to `example.ml` showing how to save.

**Comment by adayoung111** [comment]
They're very helpful. Thanks so much!

**Comment by CGenie** [comment]
And how should one add a header to this Csv generated from array of arrays?

**Comment by CGenie** [comment]
Ah I guess header isn't treated specially and for outputting one just prepends the value arrays with header array.
