### ISSUE TITLE
Fails do build with static linking

### ISSUE THREAD

**Issue by vog** [Chris00/ocaml-csv#25]
It seems that `csv` is not supposed to be linked statically - which is a very unusual limitation for a pure OCaml library.

Is that on purpose or did this happen accidentally?

Is there an easy fix for this?

The following error occurs when installing `csv` into the `4.07.1+musl+static+flambda` compiler switch:

```
#=== ERROR while compiling csv.2.1 ============================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+musl+static+flambda | https://opam.ocaml.org#1cacc413
# path        .../4.07.1+musl+static+flambda/.opam-switch/build/csv.2.1
# command     .../opam-init/hooks/sandbox.sh build dune build -p csv -j 3
...
### output ###
#        ocaml src/csv.ml (exit 2)
# (cd .../default && .../4.07.1+musl+static+flambda/bin/ocaml pp.ml)
# Cannot load required shared library dllcamlstr.
# Reason: dllcamlstr.so: dynamic loading not supported on this platform.
# Cannot load required shared library dllunix.
# Reason: dllunix.so: dynamic loading not supported on this platform.
# File "./pp.ml", line 1:
# Error: Reference to undefined global `Unix'
```

**Comment by vog** [comment]
Perhaps related issues:

* https://github.com/ocaml/opam-repository/pull/12832#issuecomment-435655528: Fix no-shared-libs error in ocaml package
* https://github.com/ocaml/opam-repository/issues/12923: Sqlite3 fails with 4.07.1+musl+static+flambda

**Comment by Chris00** [comment]
I can confirm that compiling the script make it work.

**Comment by Chris00** [comment]
Release pending: https://github.com/ocaml/opam-repository/pull/12925

**Comment by vog** [comment]
That's great! Thanks for the quick solution.
