### ISSUE TITLE
Semicolon separator give "Non-space char after closing the quoted field"

### ISSUE THREAD

**Issue by kintaro1981** [Chris00/ocaml-csv#26]
I'm on ocaml-csv-1.2.3-8.el7.x86_64.

i'm trying

`csvtool -t ';' col 2 file.csv 
`
and I get this:

`Fatal error: exception Csv.Failure(5818, 1, "Non-space char after closing the quoted field")`

same error of
https://github.com/Chris00/ocaml-csv/issues/11

I already reinstalled without lucky. 😞

**Comment by Chris00** [comment]
May you upload the file that triggers that problem?

**Comment by Chris00** [comment]
Without the file, there is little I can do.  Please reopen with an example.
