### ISSUE TITLE
Where can I read about the excel_tricks

### ISSUE THREAD

**Issue by hhugo** [Chris00/ocaml-csv#31]
and in particular about the null byte escape ?

**Comment by Chris00** [comment]
In the code ;-)
More seriously, Richard Jones is the author of these tricks (I do not use excel) and I'm not sure where he got these from — possibly in part through some experimentation.

**Comment by rwmjones** [comment]
TBH I don't recall where I read them from since it was near on 15 years ago that I wrote this library for an old job.
