### ISSUE TITLE
Documentation URL — redirects to UMons home page

### ISSUE THREAD

**Issue by clarksmr** [Chris00/ocaml-csv#42]
At the bottom of the [README](https://github.com/Chris00/ocaml-csv/blob/master/README.md) there is a link to the documentation. That URL is https://math.umons.ac.be/anum/software/csv/. At least for me, that now redirects to the UMons homepage at https://web.umons.ac.be/en/.

One possibility would be to replace the link with this: https://ocaml.org/p/csv/latest/doc/Csv/index.html.

Thank you for the great CSV library! We use it in CS 3110 at Cornell.

**Comment by Chris00** [comment]
Thanks for letting me know.  I have updated the links.
