### ISSUE TITLE
Option to preserve all whitespaces

### ISSUE THREAD

**Issue by vouillon** [Chris00/ocaml-csv#8]
There should be an option to keep whitespaces at the beginning and end of each field, following RFC 4180. In particular, Google Sheets does not quote these whitespaces.

**Comment by Chris00** [comment]
Please confirm that it works with your files.  [RFC 4180](https://tools.ietf.org/html/rfc4180) is rather vague about the use of spaces with quoted fields.  I've considered that `spaces "` at the beginning of a field means that it is quoted and the spaces are ignored (this is not allowed by the ABNF grammar however, please check how fields of the form `space "...` are encoded in the softwares you care about).

**Comment by vouillon** [comment]
It works, indeed. Thanks a lot!
